### ISSUE TITLE
Mac support limited. unable to use plugin or remove chocks

### ISSUE THREAD

**Issue by RedHawkFeather** [SimSolutions1/Issue-Tracker#25]
**Platform**
Mac Big Sur, Xplane11

**Description**
Unable to remove Chocks on Mac. Plugin isn't supported.

**Comment by slimit75** [comment]
The current public version doesn't support macOS, however this is something being worked on for the next update.

**Comment by slimit75** [comment]
Marking as closed, update should be coming later today.
