### ISSUE TITLE
G1000 Popout not remebmering position

### ISSUE THREAD

**Issue by domineum** [SimSolutions1/Issue-Tracker#39]
**Platform**
XPlane 12.0, DA40 1.2.0

**Description**
G1000 Popout Screen to Virtual-Fly G1000 Hardware is not persistent. Have to popout, drag and resize manually every time

**Comment by slimit75** [comment]
This shouldn't be too difficult to fix, will put it on the to-do list for the next update

**Comment by slimit75** [comment]
As of `7515585`, we use the new Avionics API introduced with X-Plane 12, which means the popout is managed by the sim and not us. I believe the sim remembers the position of its popouts, but that's not something I'm able to test at this second. (and even if it doesn't, I don't think that's something I can change)
